[project]
name = "music"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "diffusers>=0.34.0",
    "modal>=1.1.1",
    "pydantic>=2.11.7",
    "torch>=2.8.0",
    "transformers>=4.55.0",
]
